### ISSUE TITLE
Create calendar invites for cohort calls

### ISSUE THREAD

**Issue by abbycabs** [MozillaFestival/open-leaders-planning#18]
Details for each call (dates & times) are the syllabi
Project track: http://mzl.la/ol7-syllabus
Culture track: http://mzl.la/ol7-culture-track-syllabus

Need one recurring (every 2 weeks) event for each cohort.

**Who to invite for each cohort:**
All registered participants in that cohort - required
All registered mentors in that cohort - optional
Cohort Hosts - required (still confirming hosts - [check here](https://github.com/MozillaFestival/open-leaders-planning/issues/4))
Abby & Chad - optional

**Cohorts A-D**
Event Title: [OL7] Week X: << Title from Syllabus >> (Cohort Y)
Event description: Notes: https://mzl.la/ol7-cohort-Y (replace with cohort link)
Event location: https://zoom.us/j/5937811987

Pinging @chadsansing for Cohorts E&F details

**Comment by abbycabs** [comment]
We should get these out by EOW so people are ready for Week 2 next week

**Comment by chadsansing** [comment]
**Cohorts E & F**

Event Title: [OL7 culture track] Week X: << Title from Syllabus >> (Cohort Y)
Event description: (Grab the week's description from [this syllabus](https://drive.google.com/open?id=1dpH_LPZQ2FTUbK1y1tIDrJfYvesFp3Ivwqp1_jju-5E))
Notes: (choose the right week for the right cohort from [this folder](https://drive.google.com/open?id=1E0shI7l6YfYexj3IHeuUsDsUZ-ieaCEz))
Event location: https://zoom.us/j/5937811987

**Comment by marcwalsh** [comment]
I've created separate calendars for each Cohort and will invite everyone to the meetings also. Cohorts A-D are all up to date, I'm working on E & F now, but all links below will stay the same.

### Calendar Links

_When using iCal links it's highly recommended that the user using their calendar platform's subscription function to subscribe to the calendar feed (using the link) rather than just downloading and opening the .ics file - as this would not update if changes are made._

**Cohort A** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_tgv8rf2b42gkio04ig6sviisss%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_tgv8rf2b42gkio04ig6sviisss%40group.calendar.google.com)
**Cohort B** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_bpcstj460hremddie6vc4pv5ck%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_bpcstj460hremddie6vc4pv5ck%40group.calendar.google.com)
**Cohort C** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_kbpa9fb3g5dkmgtlaagu5tq6uk%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_kbpa9fb3g5dkmgtlaagu5tq6uk%40group.calendar.google.com)
**Cohort D** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_at5o36jcokbegdsiub524rpg38%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_at5o36jcokbegdsiub524rpg38%40group.calendar.google.com)
**Cohort E** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_n7oiid60bnri6g0543pag332uo%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_n7oiid60bnri6g0543pag332uo%40group.calendar.google.com)
**Cohort F** - [iCal](https://calendar.google.com/calendar/ical/mozilla.com_afvrn7plcr81nc68c2212t9998%40group.calendar.google.com/public/basic.ics) / [Web View](https://calendar.google.com/calendar/embed?src=mozilla.com_afvrn7plcr81nc68c2212t9998%40group.calendar.google.com)

**Comment by abbycabs** [comment]
I just clicked through the web view for Cohort A & all the times are 5 hours late (time zone issue?)

**Comment by abbycabs** [comment]
but the event descriptions are ace 👌

**Comment by marcwalsh** [comment]
Ahh I think it's because the link is localised:
 
Try this: https://calendar.google.com/calendar/embed?src=mozilla.com_tgv8rf2b42gkio04ig6sviisss%40group.calendar.google.com

otherwise it's separate Web Links for Timezones like this: https://calendar.google.com/calendar/embed?src=mozilla.com_tgv8rf2b42gkio04ig6sviisss%40group.calendar.google.com&ctz=Canada/Toronto

**Comment by abbycabs** [comment]
That worked! Can you send invites out today?

**Comment by marcwalsh** [comment]
Yeah I'll get them out by the end of my day :)

**Comment by marcwalsh** [comment]
So far I've completed invites to:

- [x] Cohort A
- [x] Cohort B
- [x] Cohort C
- [x] Cohort D
- [x] Cohort E
- [x] Cohort F

**Comment by marcwalsh** [comment]
All mentors and mentees have been invited! Going through Hosts now and then will close!

**Comment by chadsansing** [comment]
@marcwalsh - Cohort E and F calls need to be an hour later ET from Week 10 onward. We keep ET constant and let UTC change.

**Comment by marcwalsh** [comment]
Thanks for catching that @chadsansing - Weeks 10, 12 and 14 have been updated!

**Comment by chadsansing** [comment]
Thanks, @marcwalsh!

**Comment by abbycabs** [comment]
invites are out and working! Closing
